server:
  port: 7003
  servlet:
    context-path: /

spring:
  application:
    name: eureka_server_7003

eureka:
  instance:
    hostname: eureka7003.com #eureka\u670D\u52A1\u5668\u7AEF\u540D\u79F0
  client:
    #false\u8868\u793A\u4E0D\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    #false\u8868\u793A\u81EA\u5DF1\u5C31\u662F\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u804C\u8D23\u662F\u7EF4\u62A4\u670D\u52A1\u5B9E\u4F8B\uFF0C\u5E76\u4E0D\u9700\u8981\u68C0\u7D22\u670D\u52A1
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
