server:
  port: 90
  servlet:
    context-path: /

eureka:
  client:
    # 客户端不注册进eureka
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
